-- ==============================================================================
-- FIX LỖI: TẠO BẢNG PROFILES TRƯỚC (NẾU CHƯA CÓ)
-- Bảng posts tham chiếu tới profiles, nên profiles PHẢI TỒN TẠI TRƯỚC.
-- ==============================================================================

-- 1. TẠO BẢNG PROFILES (Đảm bảo bảng này có trước)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  full_name text,
  avatar_url text,
  phone text,
  email text,
  vnccid text,
  role text default 'member'
);
alter table public.profiles enable row level security;
drop policy if exists "Cong khai ho so" on public.profiles;
create policy "Cong khai ho so" on public.profiles for select using (true);
drop policy if exists "Ca nhan tu sua ho so" on public.profiles;
create policy "Ca nhan tu sua ho so" on public.profiles for update using (auth.uid() = id);

-- ==============================================================================
-- TIẾP TỤC TẠO CÁC BẢNG SOCIAL (Sau khi đã có profiles)
-- ==============================================================================

-- 2. BẢNG POSTS
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  content text,
  image_urls text[],
  author_id uuid references public.profiles(id) not null, -- Giờ đã có profiles để tham chiếu
  scope text default 'CLAN' check (scope in ('CLAN', 'FAMILY')),
  type text default 'news'
);
alter table public.posts enable row level security;
drop policy if exists "Xem bai viet" on public.posts;
create policy "Xem bai viet" on public.posts for select using (true); -- Đơn giản hóa rule để test
drop policy if exists "Dang bai" on public.posts;
create policy "Dang bai" on public.posts for insert with check (auth.role() = 'authenticated');

-- 3. BẢNG COMMENTS
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) not null,
  content text not null
);
alter table public.comments enable row level security;
drop policy if exists "Xem comment" on public.comments;
create policy "Xem comment" on public.comments for select using (true);
drop policy if exists "Comment bai viet" on public.comments;
create policy "Comment bai viet" on public.comments for insert with check (auth.role() = 'authenticated');

-- 4. BẢNG REATCTIONS
create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  type text default 'heart',
  unique(post_id, user_id)
);
alter table public.reactions enable row level security;
drop policy if exists "Ai cung xem like" on public.reactions;
create policy "Ai cung xem like" on public.reactions for select using (true);
drop policy if exists "Tha tim" on public.reactions;
create policy "Tha tim" on public.reactions for insert with check (auth.role() = 'authenticated');

-- 5. BẢNG NOTIFICATIONS
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references public.profiles(id) not null,
  actor_id uuid references public.profiles(id),
  title text,
  body text,
  type text,
  reference_id bigint,
  is_read boolean default false
);
alter table public.notifications enable row level security;
drop policy if exists "Xem thong bao cua minh" on public.notifications;
create policy "Xem thong bao cua minh" on public.notifications for select using (auth.uid() = user_id);

-- 6. TRIGGER & FUNCTION (Logic tự động thông báo)
create or replace function public.notify_on_comment() returns trigger as $$
declare
  post_author_id uuid;
begin
  select author_id into post_author_id from public.posts where id = new.post_id;
  if post_author_id != new.author_id then
    insert into public.notifications (user_id, actor_id, title, body, type, reference_id)
    values (post_author_id, new.author_id, 'Bình luận mới', 'đã bình luận vào bài viết của bạn.', 'comment', new.post_id);
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_comment_created on public.comments;
create trigger on_comment_created
  after insert on public.comments
  for each row execute procedure public.notify_on_comment();
