-- ==============================================================================
-- FULL DATABASE SETUP SCRIPT (CHẠY 1 LẦN)
-- Script này sẽ thiết lập toàn bộ các bảng cần thiết cho:
-- 1. Quản lý thành viên (Profiles)
-- 2. Sự kiện dòng họ (Giỗ chạp, Thanh minh...)
-- 3. Cây gia phả (Family Tree)
-- 4. Quỹ dòng họ (Funds)
-- ==============================================================================

-- 1. BẢNG PROFILES (Thông tin người dùng đăng nhập)
-- Tự động đồng bộ với Supabase Auth
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  full_name text,
  phone text,
  email text,
  vnccid text, -- Căn cước công dân / Định danh
  avatar_url text,
  role text default 'member' -- 'admin', 'toc_truong' (Tộc trưởng), 'member'
);

-- Bảo mật (RLS)
alter table public.profiles enable row level security;
drop policy if exists "Công khai hồ sơ" on public.profiles;
create policy "Công khai hồ sơ" on public.profiles for select using (true);
drop policy if exists "Cá nhân tự sửa hồ sơ" on public.profiles;
create policy "Cá nhân tự sửa hồ sơ" on public.profiles for update using (auth.uid() = id);

-- Trigger tự động tạo profile khi đăng ký
create or replace function public.handle_new_user() returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email, phone)
  values (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', 'Thành viên mới'), 
    new.raw_user_meta_data->>'avatar_url',
    new.email,
    new.raw_user_meta_data->>'phone'
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 2. BẢNG CLAN_EVENTS (Quản lý Sự kiện / Giỗ chạp)
create table if not exists public.clan_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  title text not null,
  description text,
  event_date date not null,       -- Ngày diễn ra
  is_lunar boolean default true,  -- True: Lịch Âm, False: Lịch Dương
  location text,                  -- Địa điểm (vd: Từ đường)
  created_by uuid references public.profiles(id)
);

alter table public.clan_events enable row level security;
create policy "Mọi người xem được sự kiện" on public.clan_events for select using (true);
create policy "Thành viên thêm sự kiện" on public.clan_events for insert with check (auth.role() = 'authenticated');


-- 3. BẢNG FAMILY_MEMBERS (Dữ liệu Cây gia phả)
create table if not exists public.family_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  full_name text not null,
  nickname text,          -- Tên thường gọi / Tên tự
  gender text check (gender in ('male', 'female', 'other')),
  
  birth_date date,
  death_date date,
  is_alive boolean default true,
  
  father_id bigint references public.family_members(id), -- Liên kết cha con
  mother_id bigint references public.family_members(id),
  spouse_id bigint references public.family_members(id), -- Vợ/Chồng
  
  generation_level int,   -- Đời thứ mấy (vd: 12)
  order_in_family int,    -- Con thứ mấy
  
  bio text,               -- Tiểu sử
  burial_place text,      -- Nơi an táng (nếu đã mất)
  
  profile_id uuid references public.profiles(id) -- Link nếu người này có dùng App
);

alter table public.family_members enable row level security;
create policy "Xem cây gia phả public" on public.family_members for select using (true);
create policy "Sửa cây gia phả (Admin/Tộc trưởng)" on public.family_members for all using (auth.role() = 'authenticated');


-- 4. BẢNG CLAN_FUNDS (Quỹ dòng họ)
create table if not exists public.clan_funds (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  title text not null,          -- Tên khoản thu/chi (vd: Đóng góp giỗ tổ 2024)
  amount numeric not null,      -- Số tiền (Dương: Thu, Âm: Chi)
  transaction_date date default now(),
  
  contributor_name text,        -- Người đóng/Người nhận
  note text,
  
  type text check (type in ('income', 'expense')) -- Thu hoặc Chi
);

alter table public.clan_funds enable row level security;
create policy "Xem quỹ công khai" on public.clan_funds for select using (true);
create policy "Quản lý quỹ" on public.clan_funds for all using (auth.role() = 'authenticated');


-- 5. DỮ LIỆU MẪU (SEED DATA) - Để app không bị trống
insert into public.clan_events (title, event_date, is_lunar, description, location) 
values 
('Giỗ Tổ Dòng Họ', '2025-03-10', true, 'Con cháu tề tựu dâng hương bái tổ', 'Từ đường dòng họ'),
('Lễ Thanh Minh', '2025-04-05', false, 'Tảo mộ tại nghĩa trang quê nhà', 'Nghĩa trang Tiên Tổ'),
('Họp mặt khuyến học', '2025-08-15', true, 'Trao quà cho các cháu đỗ đại học', 'Nhà văn hóa thôn');

insert into public.clan_funds (title, amount, type, contributor_name, note)
values
('Thu quỹ đầu năm 2025', 50000000, 'income', 'Toàn thể các chi', 'Mỗi hộ đóng góp 500k'),
('Tu sửa mái ngói từ đường', -12000000, 'expense', 'Bác Cả (Trưởng tộc)', 'Mua ngói và thuê thợ'),
('Ông Hùng (hời 12) công đức', 2000000, 'income', 'Ông Hùng', 'Cung tiến thêm vào quỹ');
