-- ==============================================================================
-- THIẾT LẬP MẠNG XÃ HỘI GIA ĐÌNH VÀ HỆ THỐNG THÔNG BÁO
-- ==============================================================================

-- 1. BẢNG POSTS (Bảng tin)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  content text,                     -- Nội dung bài viết
  image_urls text[],                -- Mảng chứa link ảnh (nếu có)
  author_id uuid references public.profiles(id) not null,
  
  scope text default 'CLAN' check (scope in ('CLAN', 'FAMILY')), -- Phạm vi hiển thị
  
  -- Type: 'news' (tin tức), 'memory' (kỷ niệm), 'alert' (báo hỷ/hiếu)
  type text default 'news'
);

-- RLS: Ai xem được bài viết?
alter table public.posts enable row level security;
create policy "Xem bài viết" on public.posts 
for select using (
  scope = 'CLAN' OR (scope = 'FAMILY' AND author_id = auth.uid()) 
  -- Note: Logic FAMILY thực tế sẽ phức tạp hơn (xem của vợ/chồng), tạm thời để chính chủ.
);
create policy "Đăng bài" on public.posts for insert with check (auth.role() = 'authenticated');



-- 2. BẢNG COMMENTS (Bình luận)
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) not null,
  content text not null
);
alter table public.comments enable row level security;
create policy "Xem comment" on public.comments for select using (true);
create policy "Comment bài viết" on public.comments for insert with check (auth.role() = 'authenticated');



-- 3. BẢNG REATCTIONS (Thả tim)
create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  type text default 'heart', -- heart, like, sad, ...
  
  unique(post_id, user_id) -- Mỗi người chỉ like 1 lần
);
alter table public.reactions enable row level security;
create policy "Ai cũng xem like" on public.reactions for select using (true);
create policy "Thả tim" on public.reactions for insert with check (auth.role() = 'authenticated');



-- 4. BẢNG NOTIFICATIONS (Thông báo) - TRÁI TIM CỦA HỆ THỐNG
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  user_id uuid references public.profiles(id) not null, -- Người nhận thông báo
  actor_id uuid references public.profiles(id),         -- Người gây ra (VD: "Bác cả" đã like)
  
  title text,
  body text,
  
  type text, -- 'comment', 'reaction', 'event_reminder', 'system'
  reference_id bigint, -- ID của bài viết hoặc sự kiện liên quan
  
  is_read boolean default false -- Trạng thái đã đọc
);
alter table public.notifications enable row level security;
create policy "Xem thông báo của mình" on public.notifications 
for select using (auth.uid() = user_id);



-- 5. FUNCTION & TRIGGER: TỰ ĐỘNG TẠO THÔNG BÁO
-- Khi ai đó Comment -> Báo cho chủ bài viết
create or replace function public.notify_on_comment() returns trigger as $$
declare
  post_author_id uuid;
begin
  -- Lấy ID tác giả bài viết
  select author_id into post_author_id from public.posts where id = new.post_id;
  
  -- Nếu tự comment bài mình thì không báo
  if post_author_id != new.author_id then
    insert into public.notifications (user_id, actor_id, title, body, type, reference_id)
    values (
      post_author_id,
      new.author_id,
      'Bình luận mới',
      'đã bình luận vào bài viết của bạn.',
      'comment',
      new.post_id
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- Gắn Trigger vào bảng Comments
drop trigger if exists on_comment_created on public.comments;
create trigger on_comment_created
  after insert on public.comments
  for each row execute procedure public.notify_on_comment();


-- 6. DỮ LIỆU MẪU (Bảng tin)
insert into public.posts (content, scope, type, author_id)
select 
  'Chào cả nhà, hôm nay trời đẹp quá!', 
  'CLAN', 
  'news',
  id 
from public.profiles limit 1; 
-- (Lấy user đầu tiên làm tác giả mẫu)
