-- advanced_genealogy_schema.sql

-- 1. Bảng Sự Kiện Gia Đình (Clan Events)
create table if not exists public.clan_events (
  id bigint generated by default as identity primary key,
  clan_id uuid references public.clans(id) on delete cascade not null,
  created_by uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  event_type text not null check (event_type in ('anniversary', 'funeral', 'wedding', 'birthday', 'gathering', 'other')), -- anniversary: Giỗ, funeral: Hiếu, wedding: Hỷ
  event_date timestamp with time zone not null,
  is_lunar_date boolean default false, -- Hỗ trợ lịch âm cho ngày giỗ
  recurrence_type text default 'none', -- none, yearly
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Phân quyền
create policy "Members can view events" on public.clan_events
  for select using (
    auth.uid() in (
      select profile_id from public.family_members where clan_id = public.clan_events.clan_id
    )
  );
  
create policy "Owners and Admins can manage events" on public.clan_events
  for all using (
    exists (
      select 1 from public.clans
      where id = public.clan_events.clan_id and owner_id = auth.uid()
    )
  );

-- 2. Bảng Tin Nhắn Chat (Chat Messages)
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete set null not null,
  receiver_id uuid references public.profiles(id) on delete set null not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone generated always as (created_at + interval '7 days') stored
);

create index if not exists idx_chat_messages_sender_receiver on public.chat_messages(sender_id, receiver_id);

create policy "Users can read their own messages" on public.chat_messages
  for select using (
    auth.uid() = sender_id or auth.uid() = receiver_id
  );

create policy "Users can send messages" on public.chat_messages
  for insert with check (
    auth.uid() = sender_id
  );

-- 3. Cập nhật bảng family_members
alter table public.family_members
  add column if not exists relation_type text default 'blood', 
  add column if not exists generation_title text, 
  add column if not exists birth_order integer,
  add column if not exists is_maternal boolean default false,
  add column if not exists permissions jsonb default '{}'::jsonb;

create index if not exists idx_family_members_vnccid on public.family_members(vnccid);

-- 4. Settings cho Profile
alter table public.profiles
  add column if not exists allow_chat boolean default true,
  add column if not exists last_login_at timestamp with time zone;
