-- Schema for Event Participation and Notifications

-- 1. Table to track Event Participants
create table if not exists public.event_participants (
  id bigint generated by default as identity primary key,
  event_id bigint references public.clan_events(id) on delete cascade not null,
  profile_id uuid references public.profiles(id) on delete cascade not null,
  status text default 'joined', -- joined, maybe, declined
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(event_id, profile_id)
);

-- RLS for participants
alter table public.event_participants enable row level security;

create policy "View participants" on public.event_participants
  for select using (
    exists (
      select 1 from public.clan_events
      join public.family_members on public.family_members.clan_id = public.clan_events.clan_id
      where public.clan_events.id = public.event_participants.event_id
      and public.family_members.profile_id = auth.uid()
    )
  );

create policy "Join events" on public.event_participants
  for insert with check (
    auth.uid() = profile_id
  );

create policy "Leave events" on public.event_participants
  for delete using (
    auth.uid() = profile_id
  );

-- 2. Simple Notifications Table (if not exists or to enhance)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  title text not null,
  body text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  data jsonb default '{}'::jsonb -- store related event_id, clan_id etc
);

alter table public.notifications enable row level security;

create policy "Users manage own notifications" on public.notifications
  for all using (auth.uid() = user_id);

-- Function to notify all clan members (to be called via RPC or client loop)
-- For simplicity in client-side, we might just insert multiple rows, 
-- but a Postgres function is cleaner for "Notify All".
create or replace function public.notify_clan_members(
  target_clan_id uuid,
  notif_title text,
  notif_body text,
  extra_data jsonb default '{}'::jsonb
) returns void as $$
begin
  insert into public.notifications (user_id, title, body, data)
  select profile_id, notif_title, notif_body, extra_data
  from public.family_members
  where clan_id = target_clan_id
  and profile_id is not null;
end;
$$ language plpgsql security definer;
