-- ==============================================================================
-- QUẢN LÝ SỰ KIỆN GIA ĐÌNH & DÒNG HỌ
-- ==============================================================================

-- 1. BẢNG EVENTS (Sự kiện)
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  
  title text not null,
  description text,
  
  -- PHẠM VI & LOẠI
  scope text default 'FAMILY' check (scope in ('FAMILY', 'CLAN')),
  clan_id uuid references public.clans(id), -- Bắt buộc nếu scope = CLAN
  
  category text check (category in ('ANNIVERSARY', 'WEDDING', 'FUNERAL', 'FESTIVAL', 'OTHER')),
  
  -- THỜI GIAN (Lưu trữ ngày Âm/Dương)
  is_lunar boolean default true,
  day int not null,           -- Ngày (1-30/31)
  month int not null,         -- Tháng (1-12)
  year int,                   -- Năm (có thể null nếu lặp lại hàng năm ko quan tâm năm gốc)
  
  -- LẶP LẠI
  recurrence_type text default 'YEARLY' check (recurrence_type in ('NONE', 'YEARLY')),
  
  -- SẮP XẾP & HIỂN THỊ (Được tính toán bởi App/Backend update)
  next_occurrence_solar date, -- Ngày dương lịch diễn ra tiếp theo
  
  created_by uuid references public.profiles(id) not null,
  
  -- TÍNH NĂNG KHÁC
  requires_attendance boolean default false -- Cần xác nhận tham gia (đồng thuận)
);

-- RLS: Ai được xem Event?
alter table public.events enable row level security;

-- Xem: 
-- 1. Sự kiện Gia Đình: Chính chủ tạo HOẶC thành viên trong gia đình (Tạm thời check auth.uid)
-- 2. Sự kiện Dòng Họ: Thành viên thuộc Clan đó
create policy "Xem sự kiện" on public.events for select using (
  (scope = 'FAMILY' and created_by = auth.uid())
  OR 
  (scope = 'CLAN' and exists (
      select 1 from public.family_members fm
      where fm.clan_id = events.clan_id 
      and fm.profile_id = auth.uid()
  ))
);

create policy "Tạo sự kiện" on public.events for insert with check (auth.role() = 'authenticated');
create policy "Sửa sự kiện" on public.events for update using (created_by = auth.uid());


-- 2. BẢNG EVENT_PARTICIPANTS (Người tham gia / Được giao việc)
create table if not exists public.event_participants (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) on delete cascade not null,
  user_id uuid references public.profiles(id) not null,
  
  role text default 'ATTENDEE' check (role in ('ASSIGNEE', 'ATTENDEE')), -- ASSIGNEE: Người được giao việc, ATTENDEE: Người tham gia
  status text default 'PENDING' check (status in ('PENDING', 'ACCEPTED', 'REJECTED')),
  
  note text, -- Ghi chú (VD: Góp 500k, Mua hoa quả...)
  
  unique(event_id, user_id)
);

alter table public.event_participants enable row level security;
create policy "Xem người tham gia" on public.event_participants for select using (true); -- Cho phép xem danh sách
create policy "Tự update trạng thái" on public.event_participants for update using (user_id = auth.uid());
create policy "Người tạo event thêm người" on public.event_participants for insert with check (
  exists (select 1 from public.events where id = event_id and created_by = auth.uid())
);


-- 3. CẬP NHẬT BẢNG NOTIFICATIONS (Thêm loại notification)
-- (Bảng này đã có từ trước, chỉ cần quy ước thêm type = 'event_reminder', 'event_assign')

-- VIEW helper để lấy events sắp tới (Optional, xử lý ở Client sẽ linh hoạt hơn với Lunar)
