
-- ==============================================================================
-- TỰ ĐỘNG THÔNG BÁO KHI CÓ SỰ KIỆN MỚI
-- ==============================================================================

-- 1. Đảm bảo bảng notifications tồn tại (nếu chưa có)
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references public.profiles(id) not null,
  title text not null,
  message text,
  type text default 'general', -- 'event_new', 'event_reminder', 'general'
  is_read boolean default false,
  related_id text -- Lưu ID của sự kiện hoặc đối tượng liên quan
);

-- Bật RLS Notification
alter table public.notifications enable row level security;
drop policy if exists "Xem thông báo của mình" on public.notifications;
create policy "Xem thông báo của mình" on public.notifications for select using (auth.uid() = user_id);


-- 2. Function xử lý trigger: Khi insert vào bảng `events` -> Tạo row trong `notifications`
create or replace function public.handle_new_event_notification()
returns trigger as $$
declare
  inviter_name text;
  target_user_id uuid;
begin
  -- Lấy tên người tạo
  select full_name into inviter_name from public.profiles where id = new.created_by;
  if inviter_name is null then inviter_name := 'Một thành viên'; end if;

  -- A. NẾU LÀ SỰ KIỆN GIA ĐÌNH (FAMILY)
  -- -> Gửi cho các thành viên trong cùng Gia Phả (Family)
  -- (Tạm thời logic này hơi phức tạp vì cần định nghĩa "cùng gia đình" là gì. 
  --  Ở đây ta tạm gửi cho những người trong cùng `clan_id` có `type='family'` nếu sự kiện có gắn clan_id loại family. 
  --  Nếu không, chỉ gửi cho người tạo (để test) hoặc bỏ qua.)
  
  -- B. NẾU LÀ SỰ KIỆN DÒNG HỌ (CLAN)
  if new.scope = 'CLAN' and new.clan_id is not null then
      -- Gửi cho TẤT CẢ thành viên thuộc Clan đó (trừ người tạo)
      insert into public.notifications (user_id, title, message, type, related_id)
      select 
          fm.profile_id,
          'Sự kiện Dòng họ mới: ' || new.title,
          inviter_name || ' đã tạo một sự kiện dòng họ mới. Hãy kiểm tra ngay!',
          'event_new',
          new.id::text
      from public.family_members fm
      where fm.clan_id = new.clan_id 
        and fm.profile_id is not null 
        and fm.profile_id != new.created_by;
  end if;

  -- C. NẾU LÀ SỰ KIỆN GIA ĐÌNH (Có chọn Gia phả cụ thể)
  if new.scope = 'FAMILY' and new.clan_id is not null then
      -- Gửi cho các thành viên trong Gia phả đó
      -- (Logic hiện tại đang giống hệt CLAN vì cùng query theo clan_id, 
      -- cần điều chỉnh query nếu FAMILY có logic thành viên khác)
      insert into public.notifications (user_id, title, message, type, related_id)
      select 
          fm.profile_id,
          'Sự kiện Gia đình mới: ' || new.title,
          inviter_name || ' đã thêm sự kiện mới cho gia đình.',
          'event_new',
          new.id::text
      from public.family_members fm
      where fm.clan_id = new.clan_id 
        and fm.profile_id is not null 
        and fm.profile_id != new.created_by;
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- 3. Gắn Trigger vào bảng Events
drop trigger if exists trigger_notify_new_event on public.events;
create trigger trigger_notify_new_event
  after insert on public.events
  for each row execute procedure public.handle_new_event_notification();
