-- Fix schema errors by dropping and recreating the events table
-- RUN THIS SCRIPT IN SUPABASE SQL EDITOR TO FIX 'generation expression is not immutable' ERROR

-- 1. DROP old tables to ensure clean slate
DROP TABLE IF EXISTS public.clan_events CASCADE;
DROP TABLE IF EXISTS public.chat_messages CASCADE; 

-- 2. Re-create Clan Events Table correctly
create table public.clan_events (
  id bigint generated by default as identity primary key,
  clan_id uuid references public.clans(id) on delete cascade not null,
  created_by uuid references public.profiles(id) on delete set null,
  title text not null,
  description text,
  event_type text not null check (event_type in ('anniversary', 'funeral', 'wedding', 'birthday', 'gathering', 'other')),
  event_date timestamp with time zone not null,
  is_lunar_date boolean default false,
  recurrence_type text default 'none',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS and Add Policies
alter table public.clan_events enable row level security;

create policy "Members can view events" on public.clan_events
  for select using (
    auth.uid() in (
      select profile_id from public.family_members where clan_id = public.clan_events.clan_id
    )
  );
  
create policy "Owners and Admins can manage events" on public.clan_events
  for all using (
    exists (
      select 1 from public.clans where id = public.clan_events.clan_id and owner_id = auth.uid()
    )
  );

-- 3. Re-create Chat Messages Table (FIXED: Removed GENERATED ALWAYS)
create table public.chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete set null not null,
  receiver_id uuid references public.profiles(id) on delete set null not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  -- Fixed: Use DEFAULT instead of GENERATED ALWAYS for stability
  expires_at timestamp with time zone default (now() + interval '7 days')
);

alter table public.chat_messages enable row level security;

create index idx_chat_messages_sender_receiver on public.chat_messages(sender_id, receiver_id);

create policy "Users can read their own messages" on public.chat_messages
  for select using (
    auth.uid() = sender_id or auth.uid() = receiver_id
  );

create policy "Users can send messages" on public.chat_messages
  for insert with check (
    auth.uid() = sender_id
  );

-- 4. Ensure columns exist on Family Members and Profiles
alter table public.family_members 
add column if not exists relation_type text default 'blood',
add column if not exists generation_title text,
add column if not exists birth_order integer,
add column if not exists is_maternal boolean default false,
add column if not exists vnccid text,
add column if not exists permissions jsonb default '{}'::jsonb;

create index if not exists idx_family_members_vnccid on public.family_members(vnccid);

alter table public.profiles
add column if not exists allow_chat boolean default true,
add column if not exists last_login_at timestamp with time zone;
