-- 1. Create table Question Bank
create table if not exists public.question_bank (
  id bigint generated by default as identity primary key,
  content text not null
);

-- IMPORTANT: Clean duplicates first to prevent Unique Constraint errors
DELETE FROM public.question_bank 
WHERE id IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER (partition BY content ORDER BY id) AS rnum
    FROM public.question_bank
  ) t
  WHERE t.rnum > 1
);

-- 2. Add Unique Constraint
ALTER TABLE public.question_bank DROP CONSTRAINT IF EXISTS question_bank_content_key;
ALTER TABLE public.question_bank ADD CONSTRAINT question_bank_content_key UNIQUE (content);

-- 3. Seed data
insert into public.question_bank (content) values 
('Tên con vật cưng đầu tiên của bạn?'),
('Thành phố nơi bố mẹ bạn gặp nhau?'),
('Tên trường tiểu học của bạn?'),
('Biệt danh hồi nhỏ của bạn là gì?'),
('Món ăn bạn ghét nhất là gì?'),
('Tên người bạn thân nhất thời thơ ấu?'),
('Chiếc xe đầu tiên bạn sở hữu?')
on conflict (content) do nothing;

-- 4. User Answers Table
-- FIX LỖI: Xóa bảng cũ nếu tồn tại để đảm bảo cấu trúc cột mới nhất luôn được cập nhật
DROP TABLE IF EXISTS public.user_security_answers CASCADE;

create table public.user_security_answers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  question text not null, 
  answer text not null,   
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. RLS
alter table public.user_security_answers enable row level security;

drop policy if exists "User view own answers" on public.user_security_answers;
create policy "User view own answers" on public.user_security_answers for select using (auth.uid() = user_id);

drop policy if exists "User update own answers" on public.user_security_answers;
create policy "User update own answers" on public.user_security_answers for all using (auth.uid() = user_id);


-- 6. RPC Function
create or replace function setup_security_answers(questions_data jsonb)
returns void as $$
declare
  item jsonb;
begin
  delete from public.user_security_answers where user_id = auth.uid();
  for item in select * from jsonb_array_elements(questions_data)
  loop
    insert into public.user_security_answers (user_id, question, answer)
    values (auth.uid(), item->>'question', item->>'answer');
  end loop;
end;
$$ language plpgsql security definer;
